### ISSUE TITLE
documentation on how to create an InlineModel

### ISSUE THREAD

**Issue by yannick** [biosustain/potion#42]
its unclear how to inline an array of models that are
connected via a one to many relationship in sqlalchemy.

further more my use case is that these being inherited models, is it possible to 
have a list of connected object that have polymorphic_identity?

**Comment by lyschoening** [comment]
Yes this could be better documented. For the time being, if you have a to-many relationship on `Foo` called `bars`, you could add a field to `FooResource.Schema` like this:

```
bars = fields.List(fields.InlineModel({
    "name": fields.String(description="Bar name"),
    "height: fields.Integer(description="Height of bar")
}, model=Bar)
```

Due to a bug in SQLAlchemy, updating a field with an inline model can cause issues. 

I don't understand the second part of your question. Potion can be made to support polymorphic models and there used to be a `contrib` package for this in the predecessor of potion, but I dropped it from potion since I didn't want to dictate one particular way of dealing with them.
