### ISSUE TITLE
id_field_class should probably be set automatically *or* schema should come from id_attribute

### ISSUE THREAD

**Issue by boydgreenfield** [biosustain/potion#61]
Rather than manually specified (with a default of `Integer`) as it is here: https://github.com/biosustain/potion/blob/ab0f7c11b0e47e395fcefb926f12f707fc01bfad/flask_potion/resource.py#L316

The specific problem is this results in `ToOne` ref schemas that erroneously say they take `anyOf` either an `Integer` or a `$ref` object (in fact this should match the `id_attribute`).

Happy to take a stab at a PR when I hear your preference for how to better disambiguate between the several ID use cases here @lyschoening. In our case, I've just manually set this to `String`, which doesn't appear to affect the underlying queries w/ a SQLAlchemy backend and fixes `$ref` schemas erroneously saying they'll take an `Integer`, but I haven't tested w/ Pewee or Mongo.

Note that the docs also appear to be out of date (say `fields.ItemUri` is default, which is only the case if `meta.include_id` is manually set to True):
https://github.com/biosustain/potion/blob/48d3cf8a7039f41770e0176fffd9374d9b7517f6/docs/quickstart.rst

**Comment by lyschoening** [comment]
Thanks for pointing out the outdated documentation. I've made a few improvements and updated the docs.

The issue here is that `id_field_class` needs to match what is in `id_attribute`. With SQLAlchemy, `id_field_class` could be looked up and overridden in `SQLAlchemyManager._init_model()` as is already done with `id_attribute`. `Resource.schema` would also have to be updated if `Meta.include_id` is true, essentially rerunning this logic: https://github.com/biosustain/potion/blob/master/flask_potion/resource.py#L215:L219

A PR would be great. Otherwise I will look at this next week.

**Comment by boydgreenfield** [comment]
I'll can also try to take a look at this Monday or Tuesday (1/4 or 1/5), but next week is fairly packed so unfortunately it may have to wait a bit (sorry!).

**Comment by lyschoening** [comment]
I have started work on this now.

**Comment by boydgreenfield** [comment]
@lyschoening Ok thanks for the heads up. I'll submit an initial PR for #57 in the next day or so.
