### ISSUE TITLE
Handling SqlAlchemy DateTime with UTC

### ISSUE THREAD

**Issue by Alain1405** [biosustain/potion#99]
In SqlAlchemy (PG backend) I have defined a timestamp as DateTime field, which should default to `timezone=false`:

```
   timestamp = db.Column(
        db.DateTime,
        nullable=False,
        server_default=func.now()
    )
```

In db the last stored timestamps is `2016-09-24 16:06:54.155689` (from pg console, no timezone present, so I assume UTC). 
If I query the potion resource I get:
```
"timestamp": {
      "$date": 1474740361000
    }
```
which is `Sat, 24 Sep 2016 18:06:01 GMT`, shifted 2h in the future.

I'm (and so the backend) in CEST (GMT+2). I let ModelResource handle the time.

Bug?

**Comment by lyschoening** [comment]
If you access the column directly, using the SQLAlchemy model, are the time and time zone in the datetime object correct? What I assume is happening is that the datetime is initialized with the local time zone instead of UTC since no timezone information is available, which would be SQLAlchemy behavior.

**Comment by Alain1405** [comment]
Actually the error was caused by using `func.now()` to set the date DB side while for some records I had it set with Python datetime. func.now() caused the current local time to be stored as UTC shifted in the future for some reason that I'm not going to investigate. :)
